version: '3.9'

services:
  fastapi:
    build:
      context: . 
      dockerfile: Dockerfile
    container_name: true-notion-ai-instance
    ports:
      - "8000:8000"
    volumes:
      - .:/app      
    env_file:
      - .env
    command: >
      uvicorn app:app --host 0.0.0.0 --port 8000 --reload